### ISSUE TITLE
Website UI Overhaul

### ISSUE THREAD

**Issue by tessamerrill** [BlueJayOne/bluejay#23]
**Is your feature request related to a problem? Please describe.**
Website isn't very A11Y friendly, wasn't very well made.

**Describe the solution you'd like**
Complete UI overhaul with TailwindUI, and more component-based layouts. Make more dashboard-like instead of whatever it is now.

**To-Do List**

- [ ] Figma Layout
- [ ] Recreate Figma Layout with Nextjs
- [ ] Add backend stuff
- [ ] Change Wordmark? (font isn't great)

**Comment by tessamerrill** [comment]
Note: This will be apart of the bot update. More to follow on that soon.

**Comment by doamatto** [comment]
~~oh finally holy sh~~
